export type ServicePageData = {
  slug: string;
  shortTitle: string;
  metaTitle: string;
  metaDescription: string;
  eyebrow: string;
  title: string;
  lead: string;
  image: string;
  imageAlt: string;
  introTitle: string;
  intro: string[];
  symptomsTitle: string;
  symptomsLead: string;
  symptoms: { title: string; text: string }[];
  scopeTitle: string;
  scopeLead: string;
  scope: { title: string; text: string }[];
  process: { title: string; text: string }[];
  estimateTitle: string;
  estimate: string[];
  checklist: string[];
  faq: [string, string][];
  related: string[];
};

export const servicePages: ServicePageData[] = [
  {
    slug: "naprawa-silnika-warszawa",
    shortTitle: "Naprawa silnika",
    metaTitle: "Naprawa silnika Warszawa Włochy | Luka Service",
    metaDescription: "Naprawa silnika w Warszawie Włochy. Sprawdzamy przyczynę wycieków, przegrzewania, spadku mocy i nierównej pracy. Zadzwoń: 690 266 302.",
    eyebrow: "Mechanika silnika | Warszawa Włochy",
    title: "Naprawa silnika w Warszawie",
    lead: "Silnik traci moc, nierówno pracuje, przegrzewa się albo zostawia plamy oleju? Najpierw ustalamy źródło problemu. Dopiero potem omawiamy możliwą naprawę, części i koszt.",
    image: "/workshop/naprawa-silnika.webp",
    imageAlt: "Naprawa rozebranego silnika w warsztacie Luka Service w Warszawie",
    introTitle: "Najpierw przyczyna, potem decyzja o naprawie.",
    intro: [
      "Podobny objaw może mieć kilka źródeł. Spadek mocy nie zawsze oznacza uszkodzenie całego silnika, a wyciek nie zawsze wymaga dużego demontażu. Dlatego zaczynamy od rozmowy o zachowaniu auta, oględzin i dobrania potrzebnych pomiarów.",
      "W Luka Service zajmujemy się zarówno usuwaniem konkretnych usterek, jak i poważniejszymi pracami przy jednostce napędowej. Wykonujemy między innymi naprawy uszczelnień, głowicy, układu chłodzenia oraz remonty silnika. Zakres zależy od wyniku sprawdzenia i stanu samochodu.",
      "Warsztat znajduje się przy ul. Pianistów 10B na warszawskich Włochach. Przyjeżdżają do nas także kierowcy z Ursusa, Ochoty i pobliskich części Warszawy. Jeśli nie wiesz, czy autem można bezpiecznie dojechać, zadzwoń przed uruchomieniem silnika.",
    ],
    symptomsTitle: "Kiedy warto umówić sprawdzenie silnika?",
    symptomsLead: "Nie czekaj, aż niewielka nieszczelność lub problem z chłodzeniem zamieni się w większą awarię. Szczególnie ważne są nowe objawy, które szybko się nasilają.",
    symptoms: [
      { title: "Nierówna praca", text: "Silnik drży, gaśnie, przerywa lub ma niestabilne obroty na zimno albo po rozgrzaniu." },
      { title: "Spadek mocy", text: "Auto wyraźnie gorzej przyspiesza, reaguje z opóźnieniem lub przechodzi w tryb awaryjny." },
      { title: "Wyciek oleju lub płynu", text: "Pod samochodem pojawiają się plamy, ubywa płynu chłodniczego albo trzeba często dolewać olej." },
      { title: "Przegrzewanie", text: "Temperatura rośnie ponad normalny poziom, wentylator pracuje długo lub pojawia się komunikat ostrzegawczy." },
      { title: "Dymienie", text: "Kolor lub ilość spalin zmienia się, szczególnie podczas rozruchu, przyspieszania albo hamowania silnikiem." },
      { title: "Niepokojące odgłosy", text: "Słychać stukanie, grzechotanie, metaliczny dźwięk lub hałas, którego wcześniej nie było." },
    ],
    scopeTitle: "Co obejmuje naprawa silnika?",
    scopeLead: "Dobieramy czynności do konkretnej usterki. Nie proponujemy remontu, jeśli problem można rozwiązać mniejszym zakresem prac.",
    scope: [
      { title: "Sprawdzenie stanu silnika", text: "Oględziny, endoskopia, pomiar kompresji i inne czynności potrzebne do potwierdzenia przyczyny objawów." },
      { title: "Uszczelnienia i wycieki", text: "Wymiana uszczelki pod głowicą, uszczelek kolektora i miski olejowej, uszczelniaczy zaworowych oraz wału korbowego." },
      { title: "Głowica silnika", text: "Demontaż, ocena stanu, przygotowanie do regeneracji, montaż oraz regulacja zaworów, gdy wymaga tego konstrukcja silnika." },
      { title: "Układ chłodzenia", text: "Sprawdzenie przyczyn przegrzewania, wymiana pompy wody, chłodnicy i nieszczelnych przewodów." },
      { title: "Naprawa lub remont", text: "Prace wewnątrz silnika i kapitalny remont wykonujemy po potwierdzeniu uszkodzeń oraz uzgodnieniu opłacalnego zakresu." },
      { title: "Kontrola po wykonaniu prac", text: "Po montażu sprawdzamy szczelność, pracę jednostki i elementy związane bezpośrednio z wykonaną naprawą." },
    ],
    process: [
      { title: "Opisujesz zachowanie auta", text: "Pytamy, kiedy pojawia się objaw, jak długo trwa i czy wcześniej wykonywano naprawy silnika." },
      { title: "Sprawdzamy i mierzymy", text: "Dobieramy oględziny oraz pomiary do objawów, żeby potwierdzić źródło problemu." },
      { title: "Omawiamy wariant naprawy", text: "Wyjaśniamy zakres, potrzebne części, możliwe ryzyka, koszt i przewidywany termin." },
      { title: "Naprawiamy po akceptacji", text: "Po wykonaniu prac kontrolujemy efekt i przekazujemy informację, co zostało zrobione." },
    ],
    estimateTitle: "Od czego zależy koszt naprawy silnika?",
    estimate: [
      "Rzetelna wycena wymaga ustalenia, który element jest uszkodzony i jak duży demontaż będzie potrzebny. Znaczenie mają też konstrukcja silnika, dostępność części oraz to, czy usterka spowodowała dalsze szkody.",
      "Po sprawdzeniu auta oddzielamy prace konieczne od dodatkowych. Jeśli podczas demontażu ujawni się problem, którego wcześniej nie dało się zobaczyć, zatrzymujemy pracę i kontaktujemy się przed rozszerzeniem zlecenia.",
    ],
    checklist: ["Zakres prac ustalony po sprawdzeniu", "Części i koszt przedstawione do akceptacji", "Dodatkowe prace tylko po kontakcie", "Kontrola wykonanej naprawy przed odbiorem"],
    faq: [
      ["Czy można wycenić naprawę silnika przez telefon?", "Przez telefon możemy omówić objawy i ustalić pierwszy krok. Dokładna wycena jest możliwa po sprawdzeniu auta, ponieważ ten sam objaw może wynikać z różnych usterek."],
      ["Czy każdy spadek mocy oznacza remont silnika?", "Nie. Przyczyną może być także problem z zasilaniem, dolotem, wydechem, turbosprężarką lub innym podzespołem. Najpierw trzeba potwierdzić źródło objawu."],
      ["Co zrobić, gdy silnik się przegrzewa?", "Zatrzymaj auto w bezpiecznym miejscu i wyłącz silnik. Nie odkręcaj gorącego zbiorniczka płynu. Zadzwoń i opisz sytuację, zanim spróbujesz jechać dalej."],
      ["Czy naprawiacie uszczelkę pod głowicą?", "Tak, taka usługa znajduje się w zakresie warsztatu. Przed rozpoczęciem prac sprawdzamy objawy i ustalamy, czy demontaż głowicy jest uzasadniony."],
      ["Czy po rozebraniu silnika koszt może się zmienić?", "Może się zdarzyć, że dopiero po demontażu widać pełny stan elementów. W takiej sytuacji przedstawiamy nowe ustalenia i czekamy na decyzję przed dalszą pracą."],
    ],
    related: ["wymiana-rozrzadu-warszawa", "diagnostyka-samochodowa-warszawa", "wymiana-oleju-warszawa-wlochy"],
  },
  {
    slug: "wymiana-rozrzadu-warszawa",
    shortTitle: "Wymiana rozrządu",
    metaTitle: "Wymiana rozrządu Warszawa Włochy | Luka Service",
    metaDescription: "Wymiana paska lub łańcucha rozrządu w Warszawie Włochy. Ustalamy właściwy zakres i części do danego silnika. Zadzwoń: 690 266 302.",
    eyebrow: "Pasek i łańcuch rozrządu | Warszawa Włochy",
    title: "Wymiana rozrządu w Warszawie",
    lead: "Nie znasz historii rozrządu, zbliża się termin wymiany lub słyszysz niepokojący dźwięk? Sprawdzimy dane samochodu i ustalimy zakres odpowiedni dla konkretnego silnika.",
    image: "/workshop/naprawa-silnika.webp",
    imageAlt: "Prace przy silniku i układzie rozrządu w warsztacie Luka Service",
    introTitle: "Rozrząd wymieniony we właściwym momencie i zakresie.",
    intro: [
      "Rozrząd synchronizuje pracę najważniejszych elementów silnika. Zużyty pasek, rolka, napinacz albo problem z łańcuchem może doprowadzić do kosztownej awarii. Termin wymiany zależy od konstrukcji jednostki, przebiegu, wieku elementów i zaleceń producenta.",
      "Przed umówieniem usługi ustalamy markę, model, rocznik, wersję silnika i dostępne informacje o wcześniejszym serwisie. Dzięki temu można dobrać właściwy zestaw części oraz sprawdzić, czy razem z rozrządem należy wymienić pompę wody, płyn chłodniczy lub inne elementy przewidziane dla tej jednostki.",
      "Jeżeli samochód ma łańcuch, nie zakładamy z góry, że trzeba go wymienić tylko dlatego, że pojawił się hałas. Najpierw oceniamy objawy i stan układu. Warsztat Luka Service mieści się przy ul. Pianistów 10B w Warszawie, dogodnie dla kierowców z Włoch, Ursusa i Ochoty.",
    ],
    symptomsTitle: "Kiedy zainteresować się rozrządem?",
    symptomsLead: "Najbezpieczniej opierać się na zaleceniach dla konkretnego silnika i udokumentowanej historii serwisowej. Brak dokumentów to powód, żeby ustalić dalsze postępowanie.",
    symptoms: [
      { title: "Zbliża się termin", text: "Przebieg lub czas od ostatniej wymiany zbliża się do wartości przewidzianej dla samochodu." },
      { title: "Brak historii serwisowej", text: "Po zakupie używanego auta nie ma rachunku, wpisu ani wiarygodnej informacji o wcześniejszej wymianie." },
      { title: "Grzechotanie po rozruchu", text: "Przez chwilę po uruchomieniu lub podczas pracy silnika pojawia się metaliczny, powtarzalny dźwięk." },
      { title: "Nierówna praca", text: "Silnik zaczął pracować inaczej, trudniej się uruchamia lub pojawił się spadek osiągów." },
      { title: "Wyciek w okolicy osłon", text: "Widoczne są ślady oleju albo płynu chłodniczego w rejonie elementów napędu rozrządu." },
      { title: "Zakup samochodu", text: "Przed zakupem lub zaraz po nim chcesz ustalić, jakie czynności serwisowe trzeba zaplanować." },
    ],
    scopeTitle: "Jak przygotowujemy wymianę rozrządu?",
    scopeLead: "Zakres nie jest identyczny w każdym samochodzie. Liczy się typ napędu rozrządu, konstrukcja silnika i dostęp do podzespołów.",
    scope: [
      { title: "Identyfikacja wersji silnika", text: "Sprawdzamy dane potrzebne do dobrania właściwych elementów, zamiast opierać się wyłącznie na ogólnej nazwie modelu." },
      { title: "Pasek rozrządu", text: "Wymieniamy pasek wraz z elementami współpracującymi przewidzianymi w zestawie, w tym rolkami i napinaczem." },
      { title: "Łańcuch rozrządu", text: "Oceniamy objawy i w uzasadnionych przypadkach wymieniamy łańcuch, ślizgi, napinacz oraz pozostałe potrzebne części." },
      { title: "Pompa wody", text: "Jeśli w danym silniku pompa współpracuje z rozrządem albo jej wymiana jest zasadna, uwzględniamy ją w ustaleniach." },
      { title: "Pasek osprzętu", text: "Podczas prac można ocenić stan dostępnego paska wielorowkowego i elementów jego prowadzenia." },
      { title: "Kontrola po montażu", text: "Sprawdzamy ustawienie, pracę silnika, szczelność i poziom płynów związanych z wykonaną usługą." },
    ],
    process: [
      { title: "Zbieramy dane auta", text: "Potrzebujemy dokładnej wersji samochodu i informacji o poprzedniej wymianie, jeśli są dostępne." },
      { title: "Dobieramy zestaw", text: "Ustalamy części oraz czynności potrzebne dla paska lub łańcucha w danym silniku." },
      { title: "Potwierdzamy koszt", text: "Przed rozpoczęciem otrzymujesz zakres, przewidywany termin i koszt do akceptacji." },
      { title: "Wymieniamy i sprawdzamy", text: "Po montażu wykonujemy kontrolę elementów związanych z usługą i pracy silnika." },
    ],
    estimateTitle: "Co wpływa na cenę wymiany rozrządu?",
    estimate: [
      "Koszt zależy przede wszystkim od wersji silnika, rodzaju rozrządu, liczby wymienianych elementów i czasu potrzebnego na dostęp do układu. Różnice między dwiema wersjami tego samego modelu mogą być duże.",
      "Dlatego przed podaniem konkretnej kwoty potrzebujemy danych samochodu. Omawiamy także wariant części i elementy, które rozsądnie wymienić przy tym samym demontażu. Nie dopisujemy dodatkowych prac bez wcześniejszego kontaktu.",
    ],
    checklist: ["Części dobrane do wersji silnika", "Zakres dla paska albo łańcucha", "Koszt potwierdzony przed rozpoczęciem", "Kontrola pracy silnika po montażu"],
    faq: [
      ["Co ile wymienia się rozrząd?", "Nie ma jednego terminu dla wszystkich aut. Interwał zależy od producenta, silnika, rodzaju układu i warunków użytkowania. Potrzebne są dokładne dane samochodu."],
      ["Czy przy rozrządzie trzeba wymienić pompę wody?", "Zależy to od konstrukcji silnika i sposobu napędu pompy. Jeśli wymiana jest przewidziana lub uzasadniona stanem elementu, uwzględniamy ją w zakresie przed pracą."],
      ["Czy łańcuch rozrządu jest bezobsługowy?", "Łańcuch zwykle nie ma tak prostego interwału jak pasek, ale jego elementy mogą się zużyć. Niepokojące dźwięki lub błędy wymagają sprawdzenia."],
      ["Kupiłem auto bez historii. Co zrobić?", "Podaj dane auta i zadzwoń. Ustalimy, jakie informacje można sprawdzić oraz czy ze względów bezpieczeństwa warto zaplanować wymianę."],
      ["Ile trwa wymiana rozrządu?", "Czas zależy od konstrukcji i zakresu. Po identyfikacji auta oraz dobraniu części podamy przewidywany termin odbioru."],
    ],
    related: ["naprawa-silnika-warszawa", "wymiana-oleju-warszawa-wlochy", "sprawdzenie-auta-przed-zakupem-warszawa"],
  },
  {
    slug: "hamulce-warszawa-wlochy",
    shortTitle: "Hamulce",
    metaTitle: "Hamulce Warszawa Włochy | Serwis Luka Service",
    metaDescription: "Serwis hamulców w Warszawie Włochy. Kontrola oraz wymiana klocków, tarcz, szczęk i elementów hamulca postojowego. Zadzwoń: 690 266 302.",
    eyebrow: "Serwis układu hamulcowego | Warszawa Włochy",
    title: "Naprawa hamulców w Warszawie",
    lead: "Pisk, drgania, dłuższa droga hamowania albo miękki pedał to sygnały, których nie warto odkładać. Sprawdzimy układ i powiemy, co wymaga naprawy teraz, a co można zaplanować później.",
    image: "/workshop/hamulce.webp",
    imageAlt: "Mechanik Luka Service kontrolujący hamulce samochodu w Warszawie",
    introTitle: "Układ hamulcowy sprawdzony jako całość.",
    intro: [
      "Skuteczność hamowania zależy nie tylko od grubości klocków. Znaczenie mają tarcze, zaciski, przewody, płyn hamulcowy, elementy tylnego układu i hamulec postojowy. Dlatego przed wymianą części sprawdzamy, skąd bierze się konkretny objaw.",
      "Jeśli auto ściąga przy hamowaniu, kierownica drży albo jedno koło wyraźnie się nagrzewa, sama wymiana klocków może nie rozwiązać problemu. Potrzebna jest ocena współpracujących elementów i swobody ich pracy.",
      "W Luka Service wykonujemy kontrolę i naprawy hamulców przy ul. Pianistów 10B na warszawskich Włochach. Obsługujemy także kierowców z Ursusa, Ochoty i okolic. Gdy hamulce działają wyraźnie gorzej, nie ryzykuj dalszej jazdy bez konsultacji.",
    ],
    symptomsTitle: "Objawy zużycia lub usterki hamulców",
    symptomsLead: "Zmiana zachowania pedału, dźwięku albo toru jazdy podczas hamowania wymaga uwagi. Szczególnie jeśli pojawiła się nagle.",
    symptoms: [
      { title: "Pisk lub tarcie", text: "Podczas hamowania słychać wysoki pisk, szuranie albo metaliczny dźwięk dochodzący z koła." },
      { title: "Drgania", text: "Pedał lub kierownica zaczyna pulsować, szczególnie przy hamowaniu z większej prędkości." },
      { title: "Auto ściąga", text: "Samochód podczas hamowania zmienia tor jazdy albo reaguje inaczej po lewej i prawej stronie." },
      { title: "Miękki pedał", text: "Pedał wpada głębiej niż zwykle, ma gąbczaste wyczucie lub wymaga kilkukrotnego naciśnięcia." },
      { title: "Kontrolka", text: "Na desce pojawiła się kontrolka układu hamulcowego, zużycia okładzin lub ABS." },
      { title: "Gorące koło", text: "Po jeździe jedno koło ma wyraźnie wyższą temperaturę albo czuć zapach przegrzanych hamulców." },
    ],
    scopeTitle: "Co sprawdzamy i naprawiamy?",
    scopeLead: "Zakres prac wynika z oględzin. Wymieniamy elementy zużyte lub uszkodzone, a nie wszystkie części według jednego schematu.",
    scope: [
      { title: "Klocki i tarcze", text: "Oceniamy zużycie, stan powierzchni roboczej oraz współpracę elementów po obu stronach osi." },
      { title: "Szczęki i tylne hamulce", text: "Sprawdzamy elementy hamulców bębnowych, ich zużycie i prawidłową pracę mechanizmu." },
      { title: "Hamulec postojowy", text: "Naprawiamy lub wymieniamy dostępne elementy odpowiedzialne za zaciąganie i zwalnianie hamulca." },
      { title: "Zaciski i prowadnice", text: "Kontrolujemy, czy klocki poruszają się swobodnie, a zacisk pracuje bez blokowania koła." },
      { title: "Przewody i płyn", text: "Sprawdzamy widoczne nieszczelności i stan przewodów oraz ustalamy potrzebę obsługi płynu hamulcowego." },
      { title: "Kontrola działania", text: "Po wykonaniu prac sprawdzamy pracę pedału i elementy objęte naprawą przed wydaniem auta." },
    ],
    process: [
      { title: "Pytamy o objaw", text: "Ustalamy, kiedy hamulce piszczą, drżą lub działają inaczej i czy problem pojawił się nagle." },
      { title: "Oglądamy układ", text: "Sprawdzamy elementy cierne, ruchome części, przewody i powiązane podzespoły." },
      { title: "Ustalamy priorytety", text: "Wskazujemy prace potrzebne dla bezpieczeństwa oraz te, które można zaplanować." },
      { title: "Naprawiamy i kontrolujemy", text: "Po akceptacji wykonujemy usługę i sprawdzamy działanie elementów objętych naprawą." },
    ],
    estimateTitle: "Jak powstaje wycena serwisu hamulców?",
    estimate: [
      "Cena zależy od konstrukcji układu, liczby wymienianych elementów, stanu zacisków i rodzaju części dobranych do auta. Przed zamówieniem materiałów sprawdzamy, czy problem dotyczy klocków i tarcz, czy także elementów, które powodują ich nierówne zużycie.",
      "Po oględzinach przedstawiamy zakres. Jeśli niektóre części nadal nadają się do bezpiecznej eksploatacji, mówimy o tym wprost. Gdy podczas pracy wyjdzie dodatkowy problem, kontaktujemy się przed zmianą kosztu.",
    ],
    checklist: ["Kontrola elementów na całej osi", "Ocena przyczyny nierównego zużycia", "Zakres i części do akceptacji", "Sprawdzenie działania po naprawie"],
    faq: [
      ["Czy klocki trzeba wymieniać razem z tarczami?", "Nie zawsze. Decyzja zależy od grubości, stanu i powierzchni tarcz oraz zaleceń dla danego układu. Oceniamy oba elementy podczas oględzin."],
      ["Dlaczego kierownica drży przy hamowaniu?", "Przyczyną mogą być między innymi tarcze, luzy lub nierówna praca elementów. Sam objaw nie wystarcza do wskazania jednej części, dlatego potrzebne jest sprawdzenie."],
      ["Czy można jechać z kontrolką hamulców?", "To zależy od komunikatu i zachowania auta, ale układ hamulcowy ma bezpośredni wpływ na bezpieczeństwo. Najlepiej zatrzymać się bezpiecznie i skonsultować dalszą jazdę."],
      ["Wymieniacie elementy hamulca postojowego?", "Tak. Zakres obejmuje wymianę zużytych szczęk oraz dostępnych elementów mechanizmu hamulca postojowego po wcześniejszej ocenie."],
      ["Czy po wymianie hamulców trzeba je docierać?", "Nowe elementy cierne potrzebują spokojnego okresu ułożenia. Przy odbiorze warto zapytać o zalecenia odpowiednie dla zastosowanych części i wykonanej pracy."],
    ],
    related: ["zawieszenie-warszawa-wlochy", "diagnostyka-samochodowa-warszawa", "sprawdzenie-auta-przed-zakupem-warszawa"],
  },
  {
    slug: "zawieszenie-warszawa-wlochy",
    shortTitle: "Zawieszenie",
    metaTitle: "Zawieszenie Warszawa Włochy | Luka Service",
    metaDescription: "Naprawa zawieszenia w Warszawie Włochy. Sprawdzamy stuki, luzy i niepewne prowadzenie. Wymiana tulei, sworzni, amortyzatorów i sprężyn.",
    eyebrow: "Zawieszenie i układ kierowniczy | Warszawa Włochy",
    title: "Naprawa zawieszenia w Warszawie",
    lead: "Auto stuka na nierównościach, pływa w zakrętach albo nierówno zużywa opony? Sprawdzimy zawieszenie i układ kierowniczy, a potem wskażemy elementy, które rzeczywiście wymagają wymiany.",
    image: "/workshop/zawieszenie.webp",
    imageAlt: "Kontrola zawieszenia samochodu na podnośniku w Luka Service",
    introTitle: "Pewne prowadzenie zaczyna się od dokładnego sprawdzenia.",
    intro: [
      "Stuk w zawieszeniu potrafi przenosić się po nadwoziu i mylić kierowcę co do miejsca usterki. Podobne dźwięki mogą pochodzić z łącznika, tulei, sworznia, mocowania amortyzatora albo elementu układu kierowniczego. Wymiana części na podstawie samego odgłosu bywa nieskuteczna.",
      "Dlatego oglądamy zawieszenie na podnośniku, sprawdzamy luzy i stan dostępnych elementów. Bierzemy pod uwagę także to, kiedy pojawia się problem: przy ruszaniu, skręcaniu, hamowaniu czy przejeżdżaniu przez krótkie nierówności.",
      "Luka Service znajduje się przy ul. Pianistów 10B na warszawskich Włochach, niedaleko Ursusa i Ochoty. Możesz umówić zarówno sprawdzenie niepokojących objawów, jak i kontrolę zawieszenia przed dłuższą trasą lub zakupem auta.",
    ],
    symptomsTitle: "Co może wskazywać na problem z zawieszeniem?",
    symptomsLead: "Nie każdy dźwięk oznacza pilną awarię, ale niepewne prowadzenie, wyraźny luz lub nagła zmiana zachowania auta powinny być sprawdzone szybko.",
    symptoms: [
      { title: "Stuki na nierównościach", text: "Słychać pojedyncze uderzenia, grzechotanie albo głuchy stuk przy progach i dziurach." },
      { title: "Niepewne prowadzenie", text: "Auto pływa, wymaga częstych korekt kierownicą lub gorzej zachowuje się w zakrętach." },
      { title: "Ściąganie", text: "Samochód nie utrzymuje kierunku albo reakcja na ruch kierownicą zmieniła się." },
      { title: "Nierówne opony", text: "Bieżnik zużywa się szybciej po jednej stronie lub na jednej osi występują wyraźne różnice." },
      { title: "Kołysanie nadwozia", text: "Po nierówności samochód dłużej się buja, nurkuje przy hamowaniu lub mocno przechyla się w zakręcie." },
      { title: "Dźwięk przy skręcie", text: "Podczas manewrowania pojawia się skrzypienie, przeskok albo stuk od przedniej części auta." },
    ],
    scopeTitle: "Zakres napraw zawieszenia",
    scopeLead: "Po sprawdzeniu wskazujemy elementy uszkodzone, elementy zbliżające się do końca eksploatacji i te, które nie wymagają działania.",
    scope: [
      { title: "Tuleje i sworznie", text: "Sprawdzamy połączenia wahaczy i wymieniamy zużyte elementy odpowiedzialne za luzy oraz stuki." },
      { title: "Łączniki i stabilizator", text: "Oceniamy części stabilizujące nadwozie, ich mocowania i możliwe źródła hałasu." },
      { title: "Amortyzatory", text: "Kontrolujemy widoczne wycieki, mocowania i objawy słabszego tłumienia; wymianę planujemy parami na osi." },
      { title: "Sprężyny", text: "Sprawdzamy pęknięcia, osiadanie oraz stan miejsc podparcia sprężyny." },
      { title: "Łożyska i przeguby", text: "Weryfikujemy luzy i odgłosy mogące pochodzić z łożysk kół lub elementów napędu." },
      { title: "Układ kierowniczy", text: "Sprawdzamy dostępne elementy, w tym końcówki, drążki i przekładnię, jeśli objawy wskazują na ten obszar." },
    ],
    process: [
      { title: "Odtwarzamy objaw", text: "Pytamy, na jakiej nawierzchni i podczas jakiego manewru pojawia się dźwięk lub luz." },
      { title: "Sprawdzamy na podnośniku", text: "Kontrolujemy połączenia, mocowania, luzy i widoczny stan elementów." },
      { title: "Wyjaśniamy wynik", text: "Pokazujemy, co wymaga naprawy, co warto obserwować i jaki będzie koszt." },
      { title: "Naprawiamy po decyzji", text: "Wymieniamy uzgodnione części i sprawdzamy obszar objęty pracą." },
    ],
    estimateTitle: "Co wpływa na koszt naprawy zawieszenia?",
    estimate: [
      "Wycena zależy od liczby zużytych elementów, konstrukcji zawieszenia, dostępu do połączeń i tego, czy część występuje osobno, czy jako większy zespół. Znaczenie ma również stan śrub i mocowań narażonych na wodę oraz sól.",
      "Po kontroli ustalamy kolejność prac. Elementy mające bezpośredni wpływ na bezpieczeństwo traktujemy jako priorytet. Pozostałe można czasem zaplanować w późniejszym terminie, jeśli ich stan na to pozwala.",
    ],
    checklist: ["Sprawdzenie luzów i mocowań", "Rozróżnienie pilnych prac od zaleceń", "Dobór części do konkretnej osi", "Kontrola po wykonaniu naprawy"],
    faq: [
      ["Czy każdy stuk oznacza uszkodzony amortyzator?", "Nie. Źródłem może być wiele elementów zawieszenia lub układu kierowniczego. Potrzebne są oględziny i sprawdzenie luzów."],
      ["Czy amortyzatory wymienia się parami?", "Zwykle wymienia się je parami na jednej osi, aby zachować zbliżoną charakterystykę tłumienia po lewej i prawej stronie."],
      ["Czy po naprawie trzeba ustawić geometrię?", "Zależy to od wymienionych elementów i konstrukcji auta. Po sprawdzeniu zakresu powiemy, czy kontrola geometrii jest potrzebna."],
      ["Czy można jeździć z luzem w zawieszeniu?", "Nie da się tego bezpiecznie ocenić bez sprawdzenia. Niektóre luzy szybko pogarszają prowadzenie i zużywają kolejne części, dlatego nie warto odkładać kontroli."],
      ["Sprawdzacie zawieszenie przed zakupem auta?", "Tak. Kontrola zawieszenia może być częścią sprawdzenia samochodu przed zakupem. Dokładny zakres ustalamy przed wizytą."],
    ],
    related: ["hamulce-warszawa-wlochy", "sprawdzenie-auta-przed-zakupem-warszawa", "diagnostyka-samochodowa-warszawa"],
  },
  {
    slug: "wymiana-oleju-warszawa-wlochy",
    shortTitle: "Wymiana oleju",
    metaTitle: "Wymiana oleju Warszawa Włochy | Luka Service",
    metaDescription: "Wymiana oleju silnikowego i filtrów w Warszawie Włochy. Dobieramy materiały do konkretnego auta i wykonujemy podstawową kontrolę przy serwisie.",
    eyebrow: "Serwis olejowy | Warszawa Włochy",
    title: "Wymiana oleju w Warszawie",
    lead: "Regularny serwis olejowy pomaga chronić silnik i wcześniej zauważyć wycieki lub zużycie. Dobieramy olej oraz filtry do konkretnej wersji auta, a zakres ustalamy przed wizytą.",
    image: "/workshop/diagnostyka.webp",
    imageAlt: "Samochód podczas obsługi serwisowej w warsztacie Luka Service",
    introTitle: "Serwis olejowy dopasowany do samochodu.",
    intro: [
      "Olej pracuje w wysokiej temperaturze, zbiera zanieczyszczenia i z czasem traci swoje właściwości. Wymiana wykonana w rozsądnym terminie jest podstawową czynnością serwisową, ale jej zakres nie powinien opierać się tylko na liczbie kilometrów.",
      "Znaczenie ma typ silnika, sposób użytkowania auta, częste krótkie trasy, jazda miejska i historia wcześniejszego serwisu. Dobieramy specyfikację i ilość oleju do konkretnej jednostki. Razem z usługą można ustalić wymianę filtrów oraz innych płynów eksploatacyjnych.",
      "Warsztat mieści się przy ul. Pianistów 10B na warszawskich Włochach, blisko Ursusa i Ochoty. Przed przyjazdem zadzwoń z danymi samochodu. Sprawdzimy dostępność materiałów i zaproponujemy termin.",
    ],
    symptomsTitle: "Kiedy zaplanować wymianę oleju?",
    symptomsLead: "Najlepiej nie czekać na kontrolkę lub pogorszenie pracy silnika. Termin warto oprzeć na zaleceniach dla auta i rzeczywistym sposobie jazdy.",
    symptoms: [
      { title: "Zbliża się interwał", text: "Od ostatniego serwisu minął zalecany czas lub samochód przejechał ustalony przebieg." },
      { title: "Nieznana historia", text: "Po zakupie używanego auta nie masz pewności, kiedy i jakim olejem wykonano poprzedni serwis." },
      { title: "Dużo jazdy miejskiej", text: "Samochód często pokonuje krótkie odcinki, stoi w korkach i rzadko osiąga pełną temperaturę pracy." },
      { title: "Komunikat serwisowy", text: "Na desce pojawiło się przypomnienie o obsłudze albo zbliżającym się terminie przeglądu." },
      { title: "Widoczny wyciek", text: "W okolicy silnika lub pod autem pojawiły się ślady oleju, których wcześniej nie było." },
      { title: "Ubytek oleju", text: "Poziom trzeba uzupełniać częściej niż zwykle lub zmieniło się tempo zużycia oleju." },
    ],
    scopeTitle: "Co możemy wykonać podczas obsługi?",
    scopeLead: "Zakres uzgadniamy według historii auta i potrzeb. Nie dokładamy czynności tylko dlatego, że samochód pojawił się na serwisie.",
    scope: [
      { title: "Olej silnikowy", text: "Dobieramy odpowiednią specyfikację i ilość, wymieniamy olej oraz filtr oleju." },
      { title: "Filtry", text: "Na życzenie i po ustaleniu zakresu wymieniamy filtr powietrza, kabinowy oraz paliwa." },
      { title: "Płyny eksploatacyjne", text: "Możemy sprawdzić potrzebę wymiany płynu chłodniczego lub hamulcowego i omówić termin obsługi." },
      { title: "Skrzynia i dyferencjały", text: "Zakres warsztatu obejmuje także wymianę oleju w skrzyni biegów i dyferencjałach po dobraniu materiału." },
      { title: "Oględziny pod autem", text: "Przy dostępie sprawdzamy widoczne wycieki i niepokojące ślady w obszarze wykonywanej usługi." },
      { title: "Kasowanie inspekcji", text: "Po wykonaniu uzgodnionego serwisu kasujemy przypomnienie serwisowe, jeśli samochód tego wymaga i umożliwia." },
    ],
    process: [
      { title: "Podajesz dane samochodu", text: "Marka, model, rocznik i silnik pozwalają przygotować właściwe materiały." },
      { title: "Ustalamy zakres serwisu", text: "Omawiamy olej, filtry i czynności wynikające z historii oraz sposobu użytkowania auta." },
      { title: "Potwierdzamy materiały i koszt", text: "Przed wizytą lub pracą wiesz, co zostanie użyte i ile wyniesie uzgodniona usługa." },
      { title: "Wykonujemy obsługę", text: "Po wymianie sprawdzamy poziom oraz obszar serwisowany i informujemy o zauważonych problemach." },
    ],
    estimateTitle: "Od czego zależy koszt wymiany oleju?",
    estimate: [
      "Na koszt wpływa ilość i specyfikacja oleju, rodzaj filtra oraz dostęp do elementów w konkretnym samochodzie. Inny zakres ma sama wymiana oleju silnikowego, a inny pełna obsługa z filtrami lub olejem przekładniowym.",
      "Po podaniu danych auta przedstawiamy dostępny wariant materiałów i zakres. Jeśli podczas obsługi zauważymy wyciek albo zużycie innego elementu, informujemy o tym. Naprawę wykonujemy dopiero po osobnym uzgodnieniu.",
    ],
    checklist: ["Olej dobrany do wersji silnika", "Zakres filtrów ustalony przed pracą", "Kontrola poziomu po wymianie", "Informacja o zauważonych nieszczelnościach"],
    faq: [
      ["Jaki olej będzie odpowiedni do mojego auta?", "Dobór zależy od wersji silnika i wymaganej specyfikacji. Podaj dane samochodu, a ustalimy właściwy materiał przed wizytą."],
      ["Czy razem z olejem trzeba wymienić filtr?", "Tak, przy wymianie oleju silnikowego standardowo uwzględnia się nowy filtr oleju. Pozostałe filtry dobieramy do uzgodnionego zakresu."],
      ["Czy kasujecie komunikat serwisowy?", "Tak, po wykonaniu odpowiedniej obsługi kasowanie inspekcji znajduje się w zakresie usług, jeśli dany samochód to umożliwia."],
      ["Czy wymieniacie olej w skrzyni biegów?", "Tak, warsztat wykonuje wymianę oleju w skrzyniach biegów i dyferencjałach. Sposób oraz materiał trzeba dobrać do konkretnego podzespołu."],
      ["Mam własny olej i filtr. Czy mogę je przywieźć?", "Najlepiej ustalić to telefonicznie przed wizytą. Trzeba potwierdzić, czy materiały mają właściwą specyfikację i pasują do samochodu."],
    ],
    related: ["wymiana-rozrzadu-warszawa", "naprawa-silnika-warszawa", "hamulce-warszawa-wlochy"],
  },
  {
    slug: "diagnostyka-samochodowa-warszawa",
    shortTitle: "Diagnostyka samochodowa",
    metaTitle: "Diagnostyka samochodowa Warszawa | Luka Service",
    metaDescription: "Diagnostyka samochodowa w Warszawie Włochy. Sprawdzamy objawy, odczytujemy błędy i szukamy przyczyny przed wymianą części. Tel. 690 266 302.",
    eyebrow: "Sprawdzenie przyczyny usterki | Warszawa Włochy",
    title: "Diagnostyka samochodowa w Warszawie",
    lead: "Kontrolka, trudny rozruch, nierówna praca albo spadek mocy? Sam kod błędu nie jest jeszcze diagnozą. Łączymy informacje z samochodu z oględzinami i objawami.",
    image: "/workshop/diagnostyka.webp",
    imageAlt: "Diagnostyka samochodu testerem w warsztacie Luka Service w Warszawie",
    introTitle: "Nie kasujemy problemu. Szukamy jego źródła.",
    intro: [
      "Diagnostyka komputerowa pozwala odczytać błędy i parametry, ale wynik trzeba właściwie zinterpretować. Kod może wskazywać obszar problemu, niekoniecznie część do natychmiastowej wymiany. Dlatego pytamy o zachowanie auta i sprawdzamy elementy powiązane z objawem.",
      "Zakres dobieramy do sytuacji. Czasem wystarcza odczyt błędów i podstawowe sprawdzenie, a czasem potrzebne są dodatkowe pomiary, oględziny mechaniczne lub obserwacja parametrów pracy. Po sprawdzeniu wyjaśniamy, co wiadomo i jaki powinien być kolejny krok.",
      "Luka Service znajduje się przy ul. Pianistów 10B na warszawskich Włochach. Obsługujemy kierowców z Włoch, Ursusa, Ochoty i pozostałych części Warszawy. Jeśli auto nie odpala, zadzwoń. Ustalimy, czy możliwa jest pomoc z dojazdem.",
    ],
    symptomsTitle: "Kiedy przydaje się diagnostyka?",
    symptomsLead: "Warto sprawdzić zarówno stały problem, jak i objaw pojawiający się tylko czasami. Przed wizytą zapamiętaj warunki, w których występuje.",
    symptoms: [
      { title: "Świeci się kontrolka", text: "Na desce pojawił się symbol silnika, ABS, poduszek, zawieszenia lub komunikat serwisowy." },
      { title: "Trudny rozruch", text: "Silnik długo kręci, uruchamia się dopiero za kolejnym razem albo gaśnie chwilę po starcie." },
      { title: "Nierówna praca", text: "Obroty falują, samochód drży, przerywa lub inaczej zachowuje się na zimnym i ciepłym silniku." },
      { title: "Spadek mocy", text: "Auto gorzej przyspiesza, ma opóźnioną reakcję lub okresowo wchodzi w tryb awaryjny." },
      { title: "Problem wraca", text: "Błąd był już kasowany albo część została wymieniona, ale objaw ponownie się pojawił." },
      { title: "Zakup używanego auta", text: "Chcesz poznać zapisane błędy i połączyć je z kontrolą stanu wybranych podzespołów." },
    ],
    scopeTitle: "Jak wygląda sprawdzenie samochodu?",
    scopeLead: "Nie każda wizyta ma identyczny przebieg. Wybieramy czynności, które mają sens dla konkretnego objawu i modelu auta.",
    scope: [
      { title: "Wywiad z kierowcą", text: "Ustalamy moment pojawienia się problemu, warunki jazdy, wcześniejsze naprawy i zachowanie kontrolek." },
      { title: "Odczyt błędów", text: "Sprawdzamy zapisane informacje i parametry dostępne w obsługiwanych systemach samochodu." },
      { title: "Weryfikacja objawu", text: "Porównujemy odczyty z rzeczywistym zachowaniem auta i widocznym stanem powiązanych elementów." },
      { title: "Pomiary i oględziny", text: "W zależności od problemu rozszerzamy sprawdzenie o potrzebne pomiary lub kontrolę mechaniczną." },
      { title: "Wskazanie kolejnego kroku", text: "Wyjaśniamy, czy można przejść do naprawy, czy potrzebne jest dalsze, bardziej szczegółowe sprawdzenie." },
      { title: "Kontrola po naprawie", text: "Gdy wykonujemy uzgodnioną naprawę, sprawdzamy objaw i powiązane błędy po zakończeniu pracy." },
    ],
    process: [
      { title: "Opisujesz warunki", text: "Im dokładniej opiszesz moment występowania problemu, tym łatwiej zaplanować sprawdzenie." },
      { title: "Zbieramy dane", text: "Odczytujemy dostępne informacje i wykonujemy oględziny związane z objawem." },
      { title: "Łączymy fakty", text: "Nie traktujemy pojedynczego kodu jako automatycznego polecenia wymiany części." },
      { title: "Przedstawiamy wniosek", text: "Omawiamy możliwą przyczynę, dalsze czynności, zakres naprawy i koszt." },
    ],
    estimateTitle: "Ile kosztuje diagnostyka samochodowa?",
    estimate: [
      "Koszt zależy od problemu i czasu potrzebnego na jego odtworzenie. Prosty odczyt zapisanych błędów różni się od szukania usterki występującej sporadycznie, wymagającej pomiarów lub rozebrania dostępnych elementów.",
      "Przed rozszerzeniem diagnostyki informujemy, jaki ma być kolejny krok. Jeśli wynik wskazuje naprawę, osobno przedstawiamy jej zakres i koszt. To pozwala podjąć decyzję bez wymiany części w ciemno.",
    ],
    checklist: ["Wywiad o rzeczywistych objawach", "Odczyt i interpretacja danych", "Sprawdzenie elementów powiązanych", "Jasny kolejny krok po diagnostyce"],
    faq: [
      ["Czy diagnostyka komputerowa wskaże uszkodzoną część?", "Nie zawsze. Kod błędu często wskazuje układ lub nieprawidłowy parametr. Trzeba powiązać go z objawami i sprawdzić możliwe przyczyny."],
      ["Czy samo skasowanie błędu rozwiąże problem?", "Kasowanie usuwa zapis, ale nie naprawia źródła usterki. Jeśli przyczyna nadal występuje, błąd lub objaw prawdopodobnie wróci."],
      ["Czy diagnozujecie auto, które nie odpala?", "Tak, ale sposób pomocy zależy od lokalizacji i objawów. Zadzwoń, aby ustalić, czy możliwy jest dojazd, czy auto powinno trafić do warsztatu."],
      ["Jak przygotować się do diagnostyki?", "Zapisz, kiedy pojawia się problem, na zimnym czy ciepłym silniku, przy jakiej prędkości i jakie kontrolki się świecą. Zabierz informacje o wcześniejszych naprawach."],
      ["Czy sprawdzacie samochód przed zakupem?", "Tak. To osobna usługa, w której zakres diagnostyki i kontroli mechanicznej ustalamy przed wizytą odpowiednio do wybranego auta."],
    ],
    related: ["sprawdzenie-auta-przed-zakupem-warszawa", "naprawa-silnika-warszawa", "zawieszenie-warszawa-wlochy"],
  },
  {
    slug: "sprawdzenie-auta-przed-zakupem-warszawa",
    shortTitle: "Sprawdzenie auta przed zakupem",
    metaTitle: "Sprawdzenie auta przed zakupem Warszawa | Luka Service",
    metaDescription: "Sprawdzenie samochodu przed zakupem w Warszawie. Diagnostyka, oględziny mechaniczne i lista zauważonych usterek przed podjęciem decyzji.",
    eyebrow: "Kontrola samochodu używanego | Warszawa Włochy",
    title: "Sprawdzenie auta przed zakupem w Warszawie",
    lead: "Ładny lakier i krótka jazda próbna nie pokazują całego stanu samochodu. Sprawdzimy wybrane podzespoły, błędy i objawy, które mogą oznaczać wydatki po zakupie.",
    image: "/workshop/diagnostyka.webp",
    imageAlt: "Sprawdzenie samochodu przed zakupem w warsztacie Luka Service",
    introTitle: "Więcej faktów przed podpisaniem umowy.",
    intro: [
      "Zakup używanego samochodu zawsze wiąże się z pewnym ryzykiem. Celem sprawdzenia nie jest obietnica, że auto nigdy się nie zepsuje. Chodzi o wychwycenie widocznych usterek, niepokojących objawów i śladów zaniedbań, które można ocenić w ustalonym zakresie wizyty.",
      "Łączymy diagnostykę z oględzinami mechanicznymi. Możemy sprawdzić między innymi zapisane błędy, pracę silnika, hamulce, zawieszenie, widoczne wycieki i stan dostępnych elementów. Dokładny zakres ustalamy wcześniej, aby kupujący i sprzedający wiedzieli, ile czasu trzeba zaplanować.",
      "Kontrola odbywa się w Luka Service przy ul. Pianistów 10B na warszawskich Włochach. Lokalizacja jest dogodna także dla osób szukających auta w Ursusie, na Ochocie i w zachodniej części Warszawy. Termin najlepiej uzgodnić przed spotkaniem ze sprzedającym.",
    ],
    symptomsTitle: "Kiedy kontrola jest szczególnie ważna?",
    symptomsLead: "W praktyce warto sprawdzić każde używane auto. Są jednak sytuacje, w których brak niezależnej kontroli oznacza większe ryzyko.",
    symptoms: [
      { title: "Brak historii serwisowej", text: "Sprzedający nie ma rachunków, wpisów ani wiarygodnych informacji o wcześniejszych naprawach." },
      { title: "Kontrolka była kasowana", text: "W pamięci mogą pozostać informacje albo gotowość systemów może wskazywać na niedawne usuwanie błędów." },
      { title: "Słychać stuki", text: "Podczas jazdy pojawiają się dźwięki z zawieszenia, silnika lub układu napędowego." },
      { title: "Silnik pracuje nierówno", text: "Rozruch trwa długo, obroty falują, widać dymienie lub czuć wyraźny spadek mocy." },
      { title: "Cena jest wyjątkowo niska", text: "Oferta mocno odbiega od podobnych samochodów i wymaga spokojnego sprawdzenia możliwych powodów." },
      { title: "Auto jest po naprawie", text: "Sprzedający informuje o większej naprawie silnika, zawieszenia lub układu hamulcowego." },
    ],
    scopeTitle: "Co możemy sprawdzić przed zakupem?",
    scopeLead: "Zakres zależy od umówionego wariantu i możliwości technicznych. Przed wizytą wyjaśniamy, co obejmie kontrola, a czego nie można wiarygodnie ocenić bez demontażu.",
    scope: [
      { title: "Diagnostyka", text: "Odczytujemy dostępne błędy i parametry, a wynik odnosimy do zachowania samochodu." },
      { title: "Silnik i osprzęt", text: "Oceniamy pracę jednostki, widoczne wycieki, niepokojące dźwięki i dostępne elementy." },
      { title: "Hamulce", text: "Sprawdzamy widoczny stan elementów ciernych i objawy mogące wpływać na skuteczność hamowania." },
      { title: "Zawieszenie i kierowanie", text: "Kontrolujemy luzy, mocowania i elementy dostępne podczas oględzin na podnośniku." },
      { title: "Płyny i ślady serwisu", text: "Zwracamy uwagę na poziomy, widoczne nieszczelności i oznaki zaniedbanej obsługi." },
      { title: "Podsumowanie usterek", text: "Przekazujemy informacje o zauważonych problemach oraz pracach, które mogą wymagać dalszej diagnostyki." },
    ],
    process: [
      { title: "Umawiasz auto i sprzedającego", text: "Podajesz dane samochodu i wspólnie wybieramy termin oraz zakres kontroli." },
      { title: "Sprawdzamy samochód", text: "Wykonujemy uzgodnione oględziny, diagnostykę i kontrolę mechaniczną." },
      { title: "Zbieramy zauważone problemy", text: "Oddzielamy wyraźne usterki od rzeczy, które wymagają dalszego sprawdzenia." },
      { title: "Omawiamy wynik", text: "Dostajesz zrozumiałe podsumowanie, które pomaga ocenić możliwe wydatki." },
    ],
    estimateTitle: "Co daje sprawdzenie auta przed zakupem?",
    estimate: [
      "Kontrola nie zastępuje całej historii pojazdu i nie pozwala zajrzeć do każdego elementu bez demontażu. Daje jednak niezależny obraz stanu dostępnych podzespołów oraz listę zauważonych problemów w chwili oględzin.",
      "Dzięki temu łatwiej zdecydować, czy auto odpowiada oczekiwaniom, czy potrzebuje dodatkowej diagnostyki i jakie naprawy mogą pojawić się po zakupie. Zakres oraz koszt sprawdzenia ustalamy przed wizytą.",
    ],
    checklist: ["Ustalony zakres przed przyjazdem", "Oględziny mechaniczne i diagnostyka", "Informacja o zauważonych usterkach", "Bez obietnic, których nie da się potwierdzić"],
    faq: [
      ["Czy sprzedający musi przyjechać do warsztatu?", "Samochód musi być dostępny w umówionym terminie, a właściciel powinien wyrazić zgodę na uzgodnione czynności. Organizację wizyty ustala kupujący ze sprzedającym."],
      ["Czy po sprawdzeniu dowiem się, czy warto kupić auto?", "Przedstawiamy stan i zauważone problemy, ale ostateczna decyzja zależy od ceny, oczekiwań oraz akceptowanego ryzyka kupującego."],
      ["Czy wykrywacie każdą ukrytą wadę?", "Nie jest to możliwe bez pełnego demontażu i długotrwałej obserwacji. Wyraźnie mówimy, co zostało sprawdzone i jakie są ograniczenia kontroli."],
      ["Ile czasu trzeba zarezerwować?", "Czas zależy od uzgodnionego zakresu i samochodu. Zadzwoń przed ustaleniem spotkania ze sprzedającym, aby zarezerwować odpowiedni termin."],
      ["Czy można od razu wycenić zauważone naprawy?", "Dla części prac możemy przedstawić dalszy sposób postępowania. Dokładna wycena zależy od poziomu rozpoznania usterki i dostępności części."],
    ],
    related: ["diagnostyka-samochodowa-warszawa", "hamulce-warszawa-wlochy", "zawieszenie-warszawa-wlochy"],
  },
];

export const servicePageBySlug = Object.fromEntries(servicePages.map((page) => [page.slug, page])) as Record<string, ServicePageData>;
